spring.application.name=DoConnectAI
spring.datasource.url=jdbc:mysql://localhost:3306/doconnectai_db
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ✅ log file name
logging.file.name=logs/appverse.log
 
# ✅ logging level
logging.level.root=INFO
logging.level.com.wipro.appverse=DEBUG
 
# ✅ pattern (optional but good)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n